#!/bin/sh

aws ec2 describe-instances --query 'Reservations[].Instances[].[Tags[?Key==`Name`].Value |[0], InstanceId, State.Name, PublicIpAddress, PrivateIpAddress, LaunchTime, VpcId, KeyName]' --output table --filters Name=tag:Name,Values="*bastion*,*Bastion*,*BASTION*"
